### ISSUE TITLE
Most Commented Media hover shows likes

### ISSUE THREAD

**Issue by CodyFraker** [preethamvishy/socialytics#8]
When you look at someone's page, and go to the "Most Commented Media" section, hover over one of the thumbnails. It'll show you the number of comments but in reality is the number of likes instead.

**Comment by preethamvishy** [comment]
Thanks for pointing that out! This has now been fixed https://github.com/preethamvishy/socialytics/commit/99dc357618246714a4731b81f00b22d69b4b9c18.

**Comment by CodyFraker** [comment]
Awesome!

What can I use to edit this angular project? I never dug into angular but wouldn't mind starting with this. Any help is appreciated.
